%{
    Define as many paths as you want in this file. Then call pathfor(<field>)
    to get the path associated with <field>. 
    
    Use fullfile(pathfor('some_folder'),'some_other_folder') to build paths relative
    to the outer paths in here.
%}

paths = struct(...
    'global_paths',         '/Volumes/My Passport/NICK/Chang Lab 2016/repositories/global/paths', ...
    'repositories',         '/Volumes/My Passport/NICK/Chang Lab 2016/repositories', ...
    'global',               '/Volumes/My Passport/NICK/Chang Lab 2016/repositories/global', ...
    'lfp',                  '/Volumes/My Passport/NICK/Chang Lab 2016/LFP/Codes/LFP', ...
    'matt',                 '/Volumes/My Passport/NICK/Chang Lab 2016/repositories/matt', ...
    'matlab_helpers',       '/Volumes/My Passport/NICK/Chang Lab 2016/repositories/matlab_helpers', ...
    'jessica',              '/Volumes/My Passport/NICK/Chang Lab 2016/repositories/jessica', ...
    'hannah',               '/Volumes/My Passport/NICK/Chang Lab 2016/repositories/hannah', ...
    'courtney',             '/Volumes/My Passport/NICK/Chang Lab 2016/repositories/courtney' ...
);

pathfile = fullfile(paths.global_paths,'global_paths.mat');

save(pathfile,'paths');


